# Generated by Django 3.2 on 2021-05-04 01:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_bid_bidder'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.ManyToManyField(related_name='listing', to='auctions.Listing')),
                ('watching', models.ManyToManyField(related_name='watching', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
